### PR TITLE
Import mysql lib and ensure unit and integration tests pass

### PR DESCRIPTION
**Pull request by shayancanonical**
# Issue
1. We developed a shared `mysql` lib in the vm charm that hasnt been ported over to the k8s charm yet. 
2. Some unittests are redundant because they are already tested in the vm charm (when developing the `mysql` lib)

# Solution
1. Import the `mysql` lib from the vm charm
2. Remove redundant unit tests
3. Make existing integration tests pass

# Context
Since the file `lib/charms/mysql/v0/mysql.py` has already been reviewed in the vm charm, there is no need to review it further.

# Release Notes
Import shared `mysql` lib from the vm charm

### CODE REVIEW

**Review by marcoppenheimer — APPROVED** [review]
See no issue with anything, must feel good to get rid of all that code!

**Review by WRFitch — APPROVED** [review]
LGTM

**Review by marceloneppel — APPROVED** [review]
LGTM!

**Comment by shayancanonical** [comment]
Thanks for the reviews!

**Pull request merged**
