### PR TITLE
DPE-3557 Workaround pvc transient error

### LINKED ISSUE #378: `create Pod mysql-k8s-1 in StatefulSet mysql-k8s failed error: failed to create PVC mysql-k8s-database-3ed48296-mysql-...` error in integration test
Found while looking at Allure reports: https://docs.google.com/spreadsheets/d/1Mc8PwHlgib0Ys535MoOVTVGazD0DDVAZ46ajJIDqljs/edit#gid=306045415&range=A2

Doesn't show up as exception in juju debug-log, potentially an issue with Juju/microk8s

Workflow run: https://github.com/canonical/mysql-k8s-operator/actions/runs/7689835900/job/20952950353

Logs (for archival purposes)
[logs-intergration-test-charm-microk8s-juju-3.1.7-high_availability-test_self_healing.py-group-1.zip](https://github.com/canonical/mysql-k8s-operator/files/14240189/logs-intergration-test-charm-microk8s-juju-3.1.7-high_availability-test_self_healing.py-group-1.zip)

juju status pytest-operator output different from log file (probably changed in time between statuses checked)
screenshot

Allure report: https://canonical.github.io/mysql-k8s-operator/1554/#suites/4c5d09a1a64e6a96d4d66ccc157cefbd/2e1cec9f38179955/

### PR DESCRIPTION
**Pull request by paulomach**
## Issue

Integration tests often fails on a [PVC failing to be created](https://github.com/canonical/mysql-k8s-operator/actions/runs/9983902668/job/27592545064#step:22:149)

## Solution

Workaround it by not raise error on wait_for_idle when run after mysql-k8s deploy/scale commands (i.e. when PVC is created)

Credits to @lucasgameiroborges 

Fixes #378

### CODE REVIEW

**Review by shayancanonical — COMMENTED** [review]
I am a little worried about the charms going into error state (for reasons other than PVC creation), and then eventually update_status coming along and setting the status as `active` and us not catching this case due to the `raise_on_error=False`

**Comment by taurus-forever** [comment]
If this really helps, why error state still failing [this](https://github.com/canonical/mysql-k8s-operator/actions/runs/10048233474/job/27772422035#step:24:123). 

Was it permanent error state and not temporary one?

**Review by taurus-forever — APPROVED** [review]

**Comment by lucasgameiroborges** [comment]
Hi guys, here to provide some context for why this change was adopted over on PostgreSQL side:

> If this really helps, why error state still failing [this](https://github.com/canonical/mysql-k8s-operator/actions/runs/10048233474/job/27772422035#step:24:123).

@taurus-forever It seems the change was missing in this particular `wait_for_idle`: https://github.com/canonical/mysql-k8s-operator/blob/ea997403bb0689886e7f5ac55888535d8304eb6c/tests/integration/test_charm.py#L65C1-L71C10

> I am a little worried about the charms going into error state (for reasons other than PVC creation), and then eventually update_status coming along and setting the status becoming active from retries and us not catching this case due to the raise_on_error=False

@shayancanonical Me and Dragomir (who originally proposed this change in the first place on my PR, I had a different approach at first) discussed the implications of not raising errors on the `wait_for_idle` calls, the main point being: It is not that we'll completely ignore the errors, it is just that they won't get raised in the very first `wait_for_idle` after charm deploy. Sure, transient errors like the PVC one might get ignored completely, but persistent errors will either get the `wait_for_idle` to timeout due to charm never getting `active` status, or something breaking further ahead in the test. About `the status becoming active from retries`, wouldn't this mean the charm actually recovered during said retries? Unless the hooks are setting `active` status when they shouldn't.

In any case, this is not a proper fix by any means, but more of a workaround to avoid annoying transient errors right after charm deploy on CI.

**Comment by paulomach** [comment]
> I am a little worried about the charms going into error state (for reasons other than PVC creation), and then eventually ~update_status coming along and setting~ the status becoming `active` from retries and us not catching this case due to the `raise_on_error=False`

As Lucas said, we will still will catch the errors, but when timeout is reached.
IMO if we can reach a better stability, It's a valid workaround.

**Pull request merged**
